### ISSUE TITLE
CasAuthenticationException when running php artisan serve

### ISSUE THREAD

**Issue by mgallegos** [XavRsl/Cas#30]
Hello!

I'm getting CasAuthenticationException when starting the laravel dev server.

I'm using Cas::authenticate() in my route file, as long as is there I get the exception.

Any ideas?

**Comment by jmandrade** [comment]
What else do you get as part of the exception?

I wouldn't use Cas:authenticate() on the routes file. I authenticate the user in a Controller method and then use a Middleware to confirm the user is authenticated.

**Comment by mgallegos** [comment]
This is the full error:

local.ERROR: exception 'Xavrsl\Cas\CasAuthenticationException' in /home/mgallegos/workspace/decima-erp/vendor/xavrsl/cas/src/Xavrsl/Cas/Sso.php:150
Stack trace:
#0 [internal function]: Xavrsl\Cas\Sso->authenticate()
#1 /home/mgallegos/workspace/decima-erp/vendor/xavrsl/cas/src/Xavrsl/Cas/CasManager.php(62): call_user_func_array(Array, Array)
#2 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(213): Xavrsl\Cas\CasManager->__call('authenticate', Array)
#3 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(213): Xavrsl\Cas\CasManager->authenticate()
#4 /home/mgallegos/workspace/decima-erp/app/Http/routes.php(102): Illuminate\Support\Facades\Facade::__callStatic('authenticate', Array)
#5 /home/mgallegos/workspace/decima-erp/app/Http/routes.php(102): Xavrsl\Cas\Facades\Cas::authenticate()
#6 [internal function]: App\Providers\RouteServiceProvider->{closure}(Object(Illuminate\Routing\Router))
#7 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(354): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#8 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(219): Illuminate\Routing\Router->group(Array, Object(Closure))
#9 /home/mgallegos/workspace/decima-erp/app/Http/routes.php(113): Illuminate\Support\Facades\Facade::__callStatic('group', Array)
#10 /home/mgallegos/workspace/decima-erp/app/Http/routes.php(113): Illuminate\Support\Facades\Route::group(Array, Object(Closure))
#11 /home/mgallegos/workspace/decima-erp/app/Providers/RouteServiceProvider.php(41): require('/home/mgallegos...')
#12 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#13 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(354): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#14 /home/mgallegos/workspace/decima-erp/app/Providers/RouteServiceProvider.php(42): Illuminate\Routing\Router->group(Array, Object(Closure))
#15 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#16 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#17 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#18 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#19 /home/mgallegos/workspace/decima-erp/app/Providers/RouteServiceProvider.php(29): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#20 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#21 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#22 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#23 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#24 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 17)
#25 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#26 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#27 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#28 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(208): Illuminate\Foundation\Application->bootstrapWith(Array)
#29 /home/mgallegos/workspace/decima-erp/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#30 /home/mgallegos/workspace/decima-erp/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 {main}

**Comment by subfission** [comment]
Hi @mgallegos, the method you are referring to, maps to a phpCAS method on a client object.  You will need to present your CAS logs for troubleshooting as they are separate from Laravel.  You may have to edit the plugin code as I do not see any configuration options for enabling debug mode.

**Comment by paszczus** [comment]
I have same problem, didn't try without artisan serve yet.

**Comment by paszczus** [comment]
I have tried with Apache and there are no error, everything is working fine!
